"""Exact-parity lookup tables: level -> {cost_mse, cost_points, prod_native, incr_mse}.

These are generated by *driving the scalar reference* (``ogame/reference.py``) level by level, so they
are exact-by-construction against the oracle (and therefore the C# source). At run time the batched env
gathers from these tables instead of computing ``pow`` in the hot loop — branchless, transcendental-free,
and exact.

Storage / dtype rationale (see plan "Precision"):
- ``*_prod`` / ``*_incr_mse`` -> **int64** (exact over the reachable range; capped at a huge sentinel
  far past any affordable level so the table never overflows).
- ``*_cost_mse`` / ``*_cost_points`` -> **float64** (costs at extreme levels are simply unaffordable;
  holding them as float64 — possibly ``inf`` — gates correctly without ever capping points or levels).

Points are never capped — maximising total points within 8000 steps is the objective; ``LMAX`` is sized
far beyond any reachable level and gathers clamp the index, so unreachable levels can never be indexed
out of range.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch

from . import reference as ref

# Far beyond any level reachable within an 8000-step episode (reaching level L in one building costs
# ~base*ratio^L resources, astronomically unaffordable well before 1024). Gathers clamp to LMAX-1.
LMAX = 1024
_INT64_MAX = 2 ** 63 - 1


def _cap_int(value: int) -> int:
    """Clamp a Python big-int to int64 range (sentinel for unreachable levels)."""
    return value if value <= _INT64_MAX else _INT64_MAX


def _safe_float(value: float) -> float:
    """float() of a Python big-int, saturating to +inf past the float64 range.

    Costs at extreme (unaffordable) levels overflow float64 — represented as ``inf``, which gates
    correctly (``resources >= inf`` is always False) without ever capping points or levels.
    """
    try:
        return float(value)
    except OverflowError:
        return float("inf")


def _mine_tables(make_mine):
    """Drive a reference mine from level 0..LMAX-1, collecting its per-level values."""
    cost_mse, cost_points, prod_native, incr_mse = [], [], [], []
    mine = make_mine()
    for _ in range(LMAX):
        cost = mine.upgrade_cost
        cost_mse.append(_safe_float(cost.convert_to_metal_value()))
        cost_points.append(_safe_float(cost.metal + cost.crystal + cost.deuterium) / 1000.0)
        prod = mine.todays_production
        prod_native.append(_cap_int(prod.metal + prod.crystal + prod.deuterium))  # single component
        incr_mse.append(_cap_int(mine.upgrade_increase_per_day.convert_to_metal_value()))
        mine.upgrade()
    return cost_mse, cost_points, prod_native, incr_mse


def _tech_tables(make_tech):
    """Drive a reference tech (astro/plasma) from level 0..LMAX-1, collecting cost values."""
    cost_mse, cost_points = [], []
    tech = make_tech()
    for _ in range(LMAX):
        cost = tech.upgrade_cost
        cost_mse.append(_safe_float(cost.convert_to_metal_value()))
        cost_points.append(_safe_float(cost.metal + cost.crystal + cost.deuterium) / 1000.0)
        tech.upgrade()
    return cost_mse, cost_points


@dataclass
class LUTs:
    """All lookup tables as device tensors, indexed by integer level."""

    # mines: cost float64, points float64, prod int64, incr int64 — shape (LMAX,)
    metal_cost_mse: torch.Tensor
    metal_cost_points: torch.Tensor
    metal_prod: torch.Tensor
    metal_incr_mse: torch.Tensor

    crystal_cost_mse: torch.Tensor
    crystal_cost_points: torch.Tensor
    crystal_prod: torch.Tensor
    crystal_incr_mse: torch.Tensor

    deut_cost_mse: torch.Tensor
    deut_cost_points: torch.Tensor
    deut_prod: torch.Tensor
    deut_incr_mse: torch.Tensor

    # techs: cost float64, points float64 — shape (LMAX,)
    astro_cost_mse: torch.Tensor
    astro_cost_points: torch.Tensor
    plasma_cost_mse: torch.Tensor
    plasma_cost_points: torch.Tensor

    lmax: int = LMAX


def build_luts(device: torch.device | str = "cpu") -> LUTs:
    """Build all lookup tables once and move them to ``device``."""
    device = torch.device(device)

    def f64(values):
        return torch.tensor(values, dtype=torch.float64, device=device)

    def i64(values):
        return torch.tensor(values, dtype=torch.int64, device=device)

    m_cost, m_pts, m_prod, m_incr = _mine_tables(ref.MetalMine)
    c_cost, c_pts, c_prod, c_incr = _mine_tables(ref.CrystalMine)
    d_cost, d_pts, d_prod, d_incr = _mine_tables(
        lambda: ref.DeuteriumSynthesizer(ref.GAME_PLANET_MAX_TEMPERATURE)
    )
    a_cost, a_pts = _tech_tables(ref.Astrophysics)
    p_cost, p_pts = _tech_tables(ref.PlasmaTechnology)

    return LUTs(
        metal_cost_mse=f64(m_cost), metal_cost_points=f64(m_pts),
        metal_prod=i64(m_prod), metal_incr_mse=i64(m_incr),
        crystal_cost_mse=f64(c_cost), crystal_cost_points=f64(c_pts),
        crystal_prod=i64(c_prod), crystal_incr_mse=i64(c_incr),
        deut_cost_mse=f64(d_cost), deut_cost_points=f64(d_pts),
        deut_prod=i64(d_prod), deut_incr_mse=i64(d_incr),
        astro_cost_mse=f64(a_cost), astro_cost_points=f64(a_pts),
        plasma_cost_mse=f64(p_cost), plasma_cost_points=f64(p_pts),
    )
