{
 "title": "Training",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Reward",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "reward", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Loss",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "loss", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Points",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "points", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Epsilon",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "epsilon", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Learning Rate",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "learning_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Points",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "points", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Value to beat",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "points", "legendFormat": "__auto" }
   ]
  }
 ]
}